### ISSUE TITLE
Error at  page navigatio

### ISSUE THREAD

**Issue by mirkarpude** [luckyseven/avatars#1]
ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: setState() called after dispose(): _AvatarState#118b4(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 4778): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 4778): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

**Comment by luckyseven** [comment]
Thank you for your feedback!

I fixed this issue in the new 2.1.0 release.

Please check it out in your project and tell me if it works! Thanks again!
