### ISSUE TITLE
Remove unecessary padding around avatar

### ISSUE THREAD

**Issue by nebiyuelias1** [luckyseven/avatars#3]
The circular avatar shape adds a bit of padding around the image. How can we remove it?
![Screenshot_1633098745](https://user-images.githubusercontent.com/25957442/135637864-d94ae256-3ffa-4157-9641-9e8d028a482b.png)

**Comment by luckyseven** [comment]
Thanks for your feedback. I've just published the `2.2.0` version of the package.

In this version you can use the `margin` parameter to remove the default card padding like this:

```
Avatar(
    margin: EdgeInsets.zero,
    name: 'Alberto Fecchi'
),

```

Let me know if you have other issues, thanks!
