### ISSUE TITLE
Firebase Storage URLs not working

### ISSUE THREAD

**Issue by Mmisiek** [luckyseven/avatars#9]
After adding image/jpg to the code, the Firebase Storage image is not loaded anyway. The avatar widget shows spinning circle.

**Comment by rensvis** [comment]
I'm using Firebase Storage images and can confirm it works like a charm. You might wanna check if you've enabled internet access in your flutter app. Otherwise, are you sure you're using the correct download url? 

>

**Comment by Mmisiek** [comment]
So I found out reason why they are not working and open another issue, I will close this one. Basically list of supported image types is too short.
